### PR TITLE
npe2 conversion (napari plugin engine 2)

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Migration to the new napari plugin engine 2 spec, see https://napari.org/stable/plugins/npe2_migration_guide.html#migrating-using-the-npe2-command-line-tool

### CODE REVIEW

**Comment by jni** [comment]
For some reason it's not detecting that I merged #10, would you mind merging in main manually (or git rebasing on main) so only the relevant changes are visible?

**Review by jni — APPROVED** [review]

**Comment by GenevieveBuckley** [comment]
> Can you also remove the napari-plugin-engine dependency, imports, and decorators? I think the convert script still assumes that one wants to support both npe1 and npe2, but that is definitely not the case anymore.

Done. Do I need to add `npe2` to the `requirements.txt` file?

**Comment by jni** [comment]
> Do I need to add npe2 to the requirements.txt file?

No, since we don't import from npe2!

We *will* need to add the yml to the manifest, but let me do that in a separate PR where I plan to update setup.py to pyproject.toml.

**Comment by jni** [comment]
(Unless you want to do it here so it stays consistent...)

**Comment by GenevieveBuckley** [comment]
What do you prefer? (I did make an issue here about pyproject.toml https://github.com/napari/napari-tiff/issues/13)

**Comment by jni** [comment]
I don't mind leaving it till the fix of #13. In we go! 😊

**Pull request merged**
